# Taps
# tap "hashicorp/tap"

# CLI tools (formulae)
brew "antidote"
brew "ast-grep"
# brew "awscli"
# brew "azure-cli"
brew "bat"
brew "biome"
# brew "bun"
brew "docker"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "git-delta"
brew "go"
# brew "golangci-lint"
# brew "goreleaser"
brew "jq"
brew "lazygit"
# brew "mysql"
brew "neovim"
brew "node"
brew "openjdk"
brew "pnpm"
brew "pi-coding-agent"
brew "python@3.14"
brew "ripgrep"
brew "starship"
brew "stow"
# brew "hashicorp/tap/terraform"
brew "tree-sitter-cli"
brew "uv"
brew "yq"
brew "zoxide"

# CLI tools (casks)
cask "claude-code"
cask "codex"
cask "copilot-cli"

# Desktop apps
cask "appcleaner"
cask "bettercmdtab"
cask "bruno"
cask "calibre"
cask "chatgpt"
cask "dbeaver-community"
cask "equinox"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "obsidian"
cask "opencode-desktop"
cask "orbstack"
cask "raycast"
cask "slack"
cask "telegram"
cask "visual-studio-code"
cask "windows-app"

# Fonts
cask "font-jetbrains-mono-nerd-font"
